[package]
name = "sonata"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
x86 = "0.44.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.2"
multiboot2 = "0.13.1"
