#ifndef _KERNEL_SIZES_H_
#define _KERNEL_SIZES_H_

#define KERNEL_BOOT_STACK_SIZE 0x40000
#define KERNEL_BOOT_STACK_ALIGNMENT 0x1000

#define TWO_MEGABYTES_SHIFT 21
#define TWO_MEGABYTES (1 << TWO_MEGABYTES_SHIFT)

#endif // _KERNEL_SIZES_H_
